print("Absolute value:")
a = abs(int(input("Enter any number")))
print("Absolute value:", a)
print()

print("Round:")
a = round(float(input("Enter any number")))
print("Round off:", a)
print()

print("Power:")
a = int(input("Enter 1st number"))
b = int(input("Enter 2nd number"))
print("Power:", pow(a, b))
print()

print("Divmod:")
a = int(input("Enter 1st number"))
b = int(input("Enter 2nd number"))
print("Divmod:", divmod(a, b))
print()

print("Addition:")
a = int(input("Enter 1st number"))
b = int(input("Enter 2nd number"))
c = int(input("Enter 3rd number"))
print("Addition:", sum([a, b, c]))
print()

print("Minimum:")
a = int(input("Enter 1st number"))
b = int(input("Enter 2nd number"))
c = int(input("Enter 3rd number"))
print("Minimum:", min(a, b, c))
print()

print("Maximum:")
a = int(input("Enter 1st number:"))
b = int(input("Enter 2nd number:"))
c = int(input("Enter 3rd number:"))
print("Maximun:", max(a, b, c))
